title: GitBook Blog
email: contact@gitbook.io
description: >
  Awesome feature and team updates about GitBook
baseurl: ""
url: "http://gitbookio.github.io/blog/"

# Build settings
markdown: kramdown

