title: GitBook Blog
email: contact@gitbook.io
description: >
  Awesome feature and team updates about GitBook
baseurl: ""
url: "https://gitbookio.github.io/blog/"
#url: "http://localhost:4000/"

# Build settings
markdown: kramdown

kramdown:
  input: GFM

gems:
  - jemoji

exclude: ["vendor"]

timezone: "US/Pacific"
